version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docai_backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app  # Mount local app code for development hot-reloading
    environment:
      - DATABASE_URL=postgresql://docai_user:docai_password@db:5432/docai_db
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    depends_on:
      - db
      - chroma
    networks:
      - docai_network

  db:
    image: postgres:15-alpine
    container_name: docai_postgres
    environment:
      POSTGRES_DB: docai_db
      POSTGRES_USER: docai_user
      POSTGRES_PASSWORD: docai_password
    volumes:
      - ./db_data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - docai_network

  chroma:
    image: chromadb/chroma:latest # Use the official ChromaDB image
    container_name: docai_chroma
    volumes:
      - ./db_data/chroma:/chroma/chroma # Persist ChromaDB data
    ports:
      - "8001:8000" # Expose ChromaDB on host port 8001
    networks:
      - docai_network

networks:
  docai_network:
    driver: bridge

