version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/docai
      - CHROMA_DB_PATH=/app/data/chroma
      - DEBUG=True
    depends_on:
      - db
      - chroma
    networks:
      - docai-network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=docai
    ports:
      - "5432:5432"
    networks:
      - docai-network

  chroma:
    image: chromadb/chroma:latest
    volumes:
      - ./data/chroma:/chroma/data
    ports:
      - "8001:8000"
    networks:
      - docai-network

volumes:
  postgres_data:

networks:
  docai-network:
    driver: bridge

